development:
  adapter: postgresql
  database: kotodama_dev
  pool: 5
  timeout: 5000
  host: localhost
  username: kotodama
  password: 'm20deqq3a'
test:
  adapter: postgresql
  database: kotodama_test
  pool: 5
  timeout: 5000
  host: localhost
  username: kotodama
  password: 'm20deqq3a'
production:
  adapter: postgresql
  database: kotodama_pro
  pool: 5
  timeout: 5000
  host: localhost
  username: kotodama
  password: 'm20deqq3a'

